### ISSUE TITLE
Set specific style of returned results (In the result list)

### ISSUE THREAD

**Issue by marjankolev** [mattzollinhofer/vue-typeahead-bootstrap#16]
Hello, 

I wanna ask if there is a possibility to set the specific style for the results that are in the list returned as a result of entered specific query.
To be more precise, I wanna remove the bolding style that is set to the first few characters of the results that are matching the written query.

Thank you very much in advance!

**Comment by RossmacD** [comment]
You can change the styling of the returned using the scoped slots, look at that section of the README for more info.
But I couldn't find a way to remove the bold part of the text easily because the htmlText that gets returned has the matching parts wrapped with a ```<strong>``` tag so I came up with a workaround for styling the highlighted text

Here is how i would do it using the example in the readme
```html
<vue-bootstrap-typeahead
  :data="countries"
  v-model="cntrySearch"
  :serializer="s => s.name"
  placeholder="Canada, United States, etc..."
  @hit="selectedCountry = $event"
>
  <!-- htmlText is bound to the matched text derived from the serializer function -->
  <template slot="suggestion" slot-scope="{ data, htmlText }">
     <span v-html="htmlText.replace(`<strong`, `<div`)"></span>
  </template>
</vue-bootstrap-typeahead>
```
What this does is it replaces ```<strong></strong>``` with ```<div></div>``` and so removes the bold highlighting

You could add a CSS class in to that div if you wanted to do more than just remove the strong styling using this in the slot instead
```html
<span v-html="htmlText.replace(`<strong`, `<div class='myClass'`)"></span>
```
I'm not sure if there is a better way to do this implemented yet but I couldn't find it in the documentation

**Comment by RossmacD** [comment]
I created this pull request in response to this
https://github.com/mattzollinhofer/vue-typeahead-bootstrap/pull/21

**Comment by mattzollinhofer** [comment]
Yeah, the proposed PR is great and I definitely expect to get merged soon.

Thanks @RossmacD! I hope it'll make life easier for you @marjankolev.

**Comment by RossmacD** [comment]
Thanks, I would definitely like to help work on other things so let me know if there is anything else specific you want me to look at doing after you look over at the new changes! 🙂

**Comment by marjankolev** [comment]
Thank you very much also from me @RossmacD ... I can't wait for the feature to be merged to master :D
And, one more question...I am already using this vue-typeahead-bootstrap component, so after the merge, did the npm update vue-typeahead-bootstrap will be enough or i have to re-install this component in my vue project?

Thank you both!
