### ISSUE TITLE
Callback triggered after item selected (aka issue 49)

### ISSUE THREAD

**Issue by billyroebuck** [mattzollinhofer/vue-typeahead-bootstrap#34]
Thanks for your work in actively maintaining this project.

I was wondering if this issue had addressed in this fork or if you know a way to solve this:
https://github.com/alexurquhart/vue-bootstrap-typeahead/issues/49

Cheers

**Comment by mattzollinhofer** [comment]
It looks like a valid concern, but an optimization that we're probably not going to look into at the moment. Thanks for bringing it to our attention, but honestly there is other work I expect will take precedence over this for a bit. I'd happily entertain discussion on a PR if you're interested in taking a look. 

I'm going to close this issue, because I don't expect to take action on this in the near term.

**Comment by billyroebuck** [comment]
thanks @mattzollinhofer . I was able to workaround the issue by storing the selected item in a variable, and then only doing the extra lookup if the current search value was different from this.
