### ISSUE TITLE
Request for `type=number`

### ISSUE THREAD

**Issue by jamie3** [mattzollinhofer/vue-typeahead-bootstrap#73]
Currently the component is set to `type=search`. This allows both alpha-numeric to be entered in the keyboard. It would be nice to be able to set it to other types such as `type=number` to limit numeric inputs.

**Comment by mattzollinhofer** [comment]
This isn't too difficult of a request, but I'm hesitant to accept every possibility because I want to ensure this project keeps a certain coherency that can get lost when you add every possible option.

Can you help me see the use case for this one? A typeahead in my mind is string matching. I assume there's a good example since you suggested it, I'm just struggling to think of it. Thanks for your thoughts!

**Comment by mattzollinhofer** [comment]
Closing for now, to keep the issues list up-to-date. Happy to reopen if additional information is provided.
